### ISSUE TITLE
How to use in multiple threads?

### ISSUE THREAD

**Issue by astro** [skade/leveldb#15]
Database implements no Clone, Send, nor Sync. The documentation however mentions:
> Multiple Database objects can be kept around, as leveldb synchronises internally.

**Comment by skade** [comment]
Thanks for pointing this out. On further reading of the leveldb docs, this isn't even true - only one pointer can be kept around.

Will fix this. (or do you want to take a go? Basically `Send` and `Sync` need to be implemented for `Database`)

**Comment by skade** [comment]
Revolved by https://github.com/skade/leveldb/commit/7b79aebae9bcd7c10cf61d207c62dc93cbb69740, see the commit for a usage example in form of a test.

**Comment by astro** [comment]
Wow, that was quick! Thank you very much.
