### ISSUE TITLE
Unimplemented trait "database::key::Key" for the type "K"

### ISSUE THREAD

**Issue by giodamelio** [skade/leveldb#17]
When building with the latest nightly (`rustc 1.5.0-nightly (cff041170 2015-09-17)`), I get this warning

    /home/giodamelio/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/leveldb-0.8.0/src/database/snapshots.rs:42:3: 42:48 warning: the trait `database::key::Key` is not implemented for the type `K` [E0277]
    /home/giodamelio/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/leveldb-0.8.0/src/database/snapshots.rs:42   fn snapshot<'a>(&'a self) -> Snapshot<'a, K>;
                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/giodamelio/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/leveldb-0.8.0/src/database/snapshots.rs:42:3: 42:48 help: run `rustc --explain E0277` to see a detailed explanation
    /home/giodamelio/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/leveldb-0.8.0/src/database/snapshots.rs:42:3: 42:48 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
    /home/giodamelio/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/leveldb-0.8.0/src/database/snapshots.rs:42   fn snapshot<'a>(&'a self) -> Snapshot<'a, K>;
                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by skade** [comment]
Fixed in #88646b4
