### ISSUE TITLE
core::fmt::String missing for error

### ISSUE THREAD

**Issue by leshow** [skade/leveldb#2]
running the example code I'm getting a 
```
the trait `core::fmt::String` is not implemented for the type `leveldb::database::error::Error` [E0277]
src/main.rs:45         Err(e) => { panic!("failed to open database: {}", e) }

```

I believe error is just missing a #[derive(Display)] in order for it to be printed to the console, am I correct?

**Comment by skade** [comment]
Eh, yes :). I cannot fix it this morning, but.

Probably better run the example in https://github.com/skade/leveldb/blob/master/src/lib.rs and lobby for this change in cargo: https://github.com/rust-lang/cargo/issues/383

The README code is currently not run as tests for that reason :(.

**Comment by skade** [comment]
Hi, I fixed the example.
