### ISSUE TITLE
Please publish new version

### ISSUE THREAD

**Issue by brson** [skade/leveldb#37]
The published 0.8.4 does not compile on arm. A new version published from master would.

**Comment by torfbolt** [comment]
Bump, ran into the same issue.

**Comment by michaelsproul** [comment]
Agreed, [Lighthouse](https://github.com/sigp/lighthouse) is eager for a new release so we can support ARM out of the box

**Comment by skade** [comment]
Published!

**Comment by brson** [comment]
Thanks @skade
